config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #create
  get "tasks/new", to: "tasks#new", as: :new
  post "tasks", to: "tasks#create"
  #Read
  get "tasks", to: "tasks#index"
  get "tasks/:id", to: "tasks#show", as: :task
  #Update 
  get "tasks/:id/edit", to: "tasks#edit"
  patch "restaurants/:id", to: "restaurants#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
      @tasks = Task.all
    end

    def show 
      @task = Task.find(params[:id])
    end

    def new
      @task = Task.new
    end

    def create
      @task = Task.new (task_params)

      if @task.save
        redirect_to tasks_path(@task)
      else
        render :new
      end
    end

    def edit
      @task = Task.find(params[:id])
      
    end

    def update
      
    end
    
    
    private 

    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.htm.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |item| %>
    <li><%= link_to item.title, task_path(item.id) %></li>
  <% end %>
</ul>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |item| %>
    <li><%= link_to item.title, task_path(item.id) %></li>
  <% end %>
</ul>

<%= link_to "Add a new tasks", new_path %>

app/views/tasks/new.html.erb
<div class="container">
<h1>New Task</h1>
<%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<h2><%= @task.title %>
<%= @task.details %>
</h2>
<%= link_to "back to list", tasks_path%>